### ISSUE TITLE
Support for attachments

### ISSUE THREAD

**Issue by nilsga** [gilbertw1/slack-scala-client#1]
It does not seem to be possible to send messages with attachments. It would be a nice added feature.

**Comment by gilbertw1** [comment]
Hi, thanks for the suggestion! I've added attachment support to posting messages. Here is what the example in the slack docs looks like:

```scala
client.postChatMessage("#general", "Hello World", attachments = Seq(Attachment(pretext = Some("pre-hello"), text = Some("text-world"))))
```

It's in master now and it'll be available once I upload the 0.1.1 release.
