### ISSUE TITLE
Client not compatible with play 2.4

### ISSUE THREAD

**Issue by pedrorijo91** [gilbertw1/slack-scala-client#20]
I'm using `"com.typesafe.play" %% "play-ws" % "2.4.3"` and I'm getting an error due to dependency conflicts. It is solved if I downgrade to `"com.typesafe.play" %% "play-ws" % "2.3.9"`

Current error:

```
Uncaught error from thread [status-notifier-akka.actor.default-dispatcher-3] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[status-notifier]
java.lang.NoClassDefFoundError: com/ning/http/client/Part
	at slack.api.SlackApiClient$.apply(SlackApiClient.scala:27)
	(...)
Caused by: java.lang.ClassNotFoundException: com.ning.http.client.Part
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more
[ERROR] [02/21/2016 12:18:17.458] [status-notifier-akka.actor.default-dispatcher-3] 
```

**Comment by gilbertw1** [comment]
Looks like the root cause is different versions of the 'async-http-client' library, used by both dispatch and play-ws. The newest version of dispatch uses the newer version of the library, and I've tested that bumping the version fixes the problem.

I just pushed a commit bumping the version of dispatch (and other dependencies as well). I'll get a new build (0.1.4), pushed to maven central in the next day or two.

**Comment by pedrorijo91** [comment]
Nice, thanks a lot !

Just letting a link to the [commit](https://github.com/gilbertw1/slack-scala-client/commit/589fcaa58ebc5a0b0f66f0d3cf231487710e94ca) here, if someone wants to track

**Comment by pedrorijo91** [comment]
still not in maven central? :/

**Comment by gilbertw1** [comment]
Yikes! I'm very sorry! I'll make sure that it's up in the next few hours

**Comment by gilbertw1** [comment]
Just released to maven central. Once it's propagated, you should be able to download the latest using "0.14". Sorry again for the delay!

**Comment by pedrorijo91** [comment]
no problem :) it's already available at http://mvnrepository.com/artifact/com.github.gilbertw1/slack-scala-client_2.11
