### ISSUE TITLE
How is the project progressing?

### ISSUE THREAD

**Issue by karlroberts** [gilbertw1/slack-scala-client#29]
Has this project stalled, how complete is the API (web and RTM) ?
Just asking, should I fork it or contribute? the reason I ask is that some old pull requests and issues have not been closed

Cheers

Karl

**Comment by gilbertw1** [comment]
Hi Karl,

The project is definitely still alive, I am however working a bit slow as I just recently had a baby. I'm planning on testing and merging the outstanding pull requests in the next few days.

Both the web and rtm implementations cover the full surface of the slack api to the best of my knowledge, although slack does have a habit of making subtle changes to the api occasionally. Feel free to contribute, my turnaround time will be much better in the future.

**Comment by karlroberts** [comment]
Hey great news. Congrats on the baby. Me too 9 weeks old.... sure slows my code down!

I will contribute and start using the code. thanks

Karl
