### ISSUE TITLE
Is this no longer published???

### ISSUE THREAD

**Issue by bwicklund** [gilbertw1/slack-scala-client#3]
```
libraryDependencies += "com.bryangilbert" %% "slack-scala-client" % "0.1.0"
```
Is not working

**Comment by adamnfish** [comment]
The `README` mentions you need to do a `publishLocal` first to make the jar available on your machine. :+1: though, it'd be much better if this was properly published.

**Comment by gilbertw1** [comment]
HI! I'll try and get this project published in short order.....been bit short on time since I put this out.

**Comment by gilbertw1** [comment]
I've uploaded the jars to sonatype and it should be available via maven central soon. One thing to note is that I've changed the goupId slightly (readme have been updated to reflect this). You should be able to import the project soon using:

libraryDependencies += "com.github.gilbertw1" %% "slack-scala-client" % "0.1.0"
