### ISSUE TITLE
Cross build to Scala 2.12

### ISSUE THREAD

**Issue by gilbertw1** [gilbertw1/slack-scala-client#37]
There are a number of dependencies that are preventing a scala 2.12 build. Unfortunately two of these dependencies: 'spray-websocket' and 'dispatch' both do not appear to be maintained any longer. Current status of each dependency:

Cross Build Checklist
- [x] akka - Supported as of 2.4.12
- [x] akka-http - supported - akka/akka-http#437
- [ ] play-json - soon to be supported - playframework/playframework#6110
- [x] dispatch - replaced with akka-http - 85fb83b
- [x] spray-websocket - replaced with akka-http websocket implementation - d8f1146

**Comment by ztaoo** [comment]
my product is waiting akka-http and play-json too.....

**Comment by 3tty0n** [comment]
akka-http may be supported for 2.12.0. 

https://github.com/akka/akka-http/issues/437

**Comment by gilbertw1** [comment]
Yep, I saw that! I'll be updating the project soon. I don't think dispatch will be updated to 2.12 anytime soon, so I still need to pull that out and replace it.

I would like to replace it with Akka-http since I'm using that for the web socket implementation. Unfortunately, requiring an actor system or materializer would bloat the  interface to the api client. So I'm not 100% sure what I'm going to replace dispatch with yet, but I plan on having 2.12 support by the end of next week.

**Comment by emptyflash** [comment]
For what it's worth, in terms of external API, it isn't super different to have an implicit `ActorSystem` or `ActorMaterializer` vs `ExecutionContext`. It's just a matter of if you want this project to be standalone, or live in the akka ecosystem.

Definitely looking forward to 2.12 support no matter what path you choose 👍

**Comment by gilbertw1** [comment]
@emptyflash: Thanks for the feedback! I decided to go ahead and just move forward using akka-http (especially since it was required already for the websocket implementation) for the http client. The main change is that now both the RTM client and the API clients require an actor system in implicit scope.

All of the akka-http related changes are in the '0.2.0-SNAPSHOT'. I've had the akka-http websocket implementation running with about a month of uptime in slack at my job, so I feel pretty confident in it. I plan on making a full 0.2.0 release once I'm able to get a 2.12 friendly version of 'play-json'.

Thanks for the patience!

**Comment by emptyflash** [comment]
@gilbertw1 that's awesome, just got the changes, and everything is working well. 👍 💯 🔥

**Comment by 3tty0n** [comment]
playframework might be supported for scala 2.12.0 https://github.com/playframework/playframework/pull/6691

**Comment by gilbertw1** [comment]
Thanks for the heads up! I've been following this thread and while 2.12 support is in master, this is for the 2.6 release of play and there currently isn't any releases out for it yet.

**Comment by gmethvin** [comment]
@gilbertw1 play-json now has a 2.6.0-M1. play-json has been split out into a separate project (
https://github.com/playframework/play-json) from playframework. Not many changes have been made since 2.5.0 so it should be a fairly clean upgrade though.

**Comment by gilbertw1** [comment]
Awesome, thanks for the heads up! With any luck I'll have a cross build for 2.12 out by the end of day.

**Comment by gilbertw1** [comment]
Scala 2.12 support added in 5645ba4 😄 

I've also released 0.2.0 to maven central cross built for both 2.11 and 2.12. Should be available in a couple hours. Thanks for the patience!
