### ISSUE TITLE
any chance of making SlackRtmConnectionActor not private?

### ISSUE THREAD

**Issue by kryton** [gilbertw1/slack-scala-client#39]
I have a custom SlackRtmConnection and it stopped working as the actor was made private.

**Comment by gilbertw1** [comment]
Hi, sorry for breaking your use case! My intention was to improve the api surface by hiding what I considered to be more implementation details and not part of the public facing api. I'm currently in the process of adding much more robust documentation, so that the generated scaldoc will be much more useful for new and existing users.

Are you constructing the ```SlackRtmConnectionActor``` directly in your code, or are you attempting to grab it from a ```SlackRtmClient``` (e.g ```rtmClient.actor```)? If it's the latter case, I'd be willing to make the ```actor``` field on ```SlackRtmClient``` non-private. If it's the former case would you consider putting your custom ```SlackRtmConnection``` inside the ```slack.rtm``` package namespace to which it's limited to?

Also, if your willing to share, I'm curious what you're doing in your custom SlackRtmConnection. If there's anything you think might be an improvement that could be made to the one provided in this library so that it would better meet your needs.

Sorry again for the inconvenience!

**Comment by kryton** [comment]
I actually re-wrote/copied SlackRtmClient.

1. I added extra commands (list of Channels & list of Users)

2. I added a way so that an actor can 'listen' to messages for a specific user/channel. I also 'watch' them, and look for the Terminated message to remove the listener. So I actually moved the 'listeners' to SlackRtmClient from SlackRtmConnectionActor.

3. I added a way to send an attachment. (I have a web-server built in so I should be able to get the button notificiations/callbacks soon)

my use case here is to to have 1 SlackRTMClient per slack installation, and have multiple bots connect in via it to communicate, with most of the intelligence sitting in other places.
I might even add a command so that I can filter messages with a certain prefix to a specific listener.
(eg. $ XXX to actor X and ! XXXX to actor Y ) 
and then enable X to spawn a child actor which holds state about the connection and only 'sees' messages it cares about (which is the main part of #2) 

I tried moving my SlackRtmClient to slack.rtm, but it still can't see the private SlackRtmConnectionActor for some reason.

**Comment by kryton** [comment]
I'll write a pull request to get this functionality into the right places in your implementation.
are you 'wed' to using a mutable to hold your listeners or would you prefer this to use context.become() and pass them into the receive function? (I think I have 2 new maps for specific channel/user -> actor & actor -> channel/user mapping.. and probably will add another 2 for user -> actor listen messages).

**Comment by gilbertw1** [comment]
Thanks, I think these will be useful additions! 

I'm not completely tied to using a mutable map to hold the listeners, although it is a fairly simple approach. I haven't taken the approach you mentioned before, but I'm open to it. You would essentially be replacing the current receive function each time a listener is added or removed with a new closure containing new immutable references to the updated listener maps?

Also, FWIW I created a simple project successfully using the ```SlackRtmConnectionActor``` directly from the ```slack.rtm``` namespace: 

https://gist.github.com/7abe262e3c0bb383e65ab97015b23f2e

This may help you get up and running until the above changes are integrated.

**Comment by gilbertw1** [comment]
A simpler option to add support for listening to specific users/channels might be to either add or enhance the existing HandlerActors in ```SimpleEventHandlers.scala``` . Eg:

```scala
private[rtm] object MessageHandlerActor {
  def apply(f: (Message) => Unit, channelId: Option[String] = None)(implicit arf: ActorRefFactory): ActorRef = {
    arf.actorOf(Props(new MessageHandlerActor(f, channelId)))
  }
}

private[rtm] class MessageHandlerActor(f: (Message) => Unit, channelId: Option[String]) extends Actor with ActorLogging {
  def receive = {
    case m: Message if channelId.isEmpty || m.channel == channelId.get =>
      try {
        f(m)
      } catch {
        case e: Exception =>
          log.error(e, "Caught exception in message handler")
      }
    case _ =>
  }
}

...
  // in the client
  def onMessageForChannel(channel: String)(f: (Message) => Unit): ActorRef = {
    val handler = MessageHandlerActor(f, Some(state.getChannelForName(channel)))
    addEventListener(handler)
    handler
  }

```

This might be simpler and wouldn't require multiple listener maps and wouldn't require all filtering to be added in inside the ```SlackRtmConnectionActor```. Additionally this would make it easier to add more of this type of functionality in the future without changing or putting more logic in the Connection Actor each time.

**Comment by kryton** [comment]
Thanks for the tips.
I remember the other reason I rewrote it.
I made it a separate Actor so I could hold the state in one place, and have either other actors, or the website communicate it. (and it wouldn't know or care).
I think if I didn't do this, I would have to have multiple SlackRTMClient's around the place instead of just the actor reference.

**Comment by gilbertw1** [comment]
Well apart from not having your additions, you should be able to share the Rtm client around fairly freely as it's mostly thread safe and doesn't maintain any state that another piece of code could manipulate directly. The only real caveat being if another piece of code were to call ```close```.

All pieces of code would be communicating directly with the actor via the client and as such wouldn't affect each other in any way.

Although it's very possible that your use case is much more nuanced in ways that I'm not fully aware of. Is your project open source anywhere? Either way, I still think a lot of the changes you mentioned would be beneficial to the project.

**Comment by kryton** [comment]
the code is here - https://github.com/kryton/SlackBot2
It's still quite raw.

the aim of it is:
1. to be able to talk to multiple Slack instances at one time
2. to be able to talk to multiple external systems (for now our Incident DB, and commerce site, but will also be Jira, and other things)
 and communicate via various messaging systems. (eg FB, WeChat, MicrosoftTeam etc)
