### ISSUE TITLE
EntityStreamSizeException: actual entity size (None) exceeded content length limit (8388608 bytes)!

### ISSUE THREAD

**Issue by martinb3** [gilbertw1/slack-scala-client#50]
Hello! After upgrading to 0.2.0, I'm seeing this error below whenever I try to use the RTM functionality against my Slack instance. I was also able to successfully bisect the issue back to this commit: https://github.com/gilbertw1/slack-scala-client/commit/85fb83b116fb3c1184e147b41b35c8bab2f9f81f. I'm not sure why the new HTTP client has such a limit, or why Slack exceeds it on connect immediately (not sure what it sends!).

```
[WARN] [03/08/2017 07:35:24.711] [org_mbs3_trivial-akka.actor.default-dispatcher-4] [akka.actor.ActorSystemImpl(org_mbs3_trivial)] Illegal response header: Illegal 'expires' header: Illegal weekday in date 1997-07-26T05:00:00: is 'Mon' but should be 'Sat'
[error] (run-main-0) EntityStreamSizeException: actual entity size (None) exceeded content length limit (8388608 bytes)! You can configure this by setting `akka.http.[server|client].parsing.max-content-length` or calling `HttpEntity.withSizeLimit` before materializing the dataBytes stream.
EntityStreamSizeException: actual entity size (None) exceeded content length limit (8388608 bytes)! You can configure this by setting `akka.http.[server|client].parsing.max-content-length` or calling `HttpEntity.withSizeLimit` before materializing the dataBytes stream.
	at akka.http.scaladsl.model.HttpEntity$Limitable$$anon$1.onPush(HttpEntity.scala:620)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:747)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:649)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:471)
	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:423)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:603)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:618)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:529)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by oshev** [comment]
I have the same problem. :(

**Comment by Garima-007** [comment]
same problem. 
If I use the earlier version of this library, can I get rid of this problem?

**Comment by gilbertw1** [comment]
akka-http was introduced as of 0.2.0, so anything older than that will use spray-websockets. 

I've yet to encounter this problem personally, and am having trouble figuring out what could be the cause. If any of you are willing, I'd really appreciate it if you could capture the response from slack that is resulting in this failure using something like wireshark, That'd be a huge help in tracking down the source of this bug.

**Comment by martinb3** [comment]
@gilbertw1 I'm not sure what to send you exactly, but it seems like this is really common from folks using akka-http when there's not a content-length header in responses, e.g.: https://github.com/hseeberger/akka-sse/issues/101

There's also some interesting content here, but not sure if it's related:
https://groups.google.com/forum/#!topic/akka-user/DIZ2WY97dnA

A Wireshark capture of this won't help b/c it's TLS encrypted -- is there a way to get the akka-http library to dump wire-level traces?

**Comment by gilbertw1** [comment]
Thanks for the pointer! Could you test this using this build: 

https://github.com/gilbertw1/slack-scala-client/releases/tag/entity-no-limit

I've removed the entity size limit in the http client, hopefully this will solve the problem. If the exception exists in the websocket client, it may be a bit more complex of an issue to solve.

Thanks!

**Comment by martinb3** [comment]
I'll test as soon as I can -- unfortunately, the bump in versions of Scala and Play between the last working one and your test build mean I've got some wrangling to do in my project to catch it up so that I'm using the same versions you are (multiple versions of Play = bad news for the classpath and compilation). More soon!

**Comment by martinb3** [comment]
Hi there -- managed to update my project. Your build doesn't seem to resolve the issue. I was able to run with the system property `-Dakka.http.client.parsing.max-content-length=512m` and that fixed my problem, so I think that indicates there's a workaround as well as implicates akka-http.

**Comment by gilbertw1** [comment]
Awesome! That was going to be my next suggestion, although I wanted to try the one above first to try and produce an in code solution. I'll have to look into it more, but on initial pass there doesn't seem to be an easy way to customize the entity limit when using the websocket functionality.

Thanks a ton for helping debug this problem....I kinda wish it'd happen to me so I could debug possible solutions more easily.

**Comment by martinb3** [comment]
@gilbertw1 Howdy! You bet. I assume it's from a very large Slack instance, maybe a lot of data to push through on the initial Websocket connection? Anyway, let me know if I should close this, or we should leave it open so we can document the property to adjust 👍

**Comment by gilbertw1** [comment]
@martinb3 Let's leave it open, I plan on documenting this heavily in the Readme. However, I'm still hoping to find code only solution that won't require an additional configuration setting to function properly.

**Comment by gilbertw1** [comment]
I've added a reference.conf file that sets a default `client.parsing.max-content-length` size of 128mb. This should solve the problem in the future, unless it is explicitly overridden with a smaller value.
