### ISSUE TITLE
Support for Scala 2.10

### ISSUE THREAD

**Issue by otrebski** [gilbertw1/slack-scala-client#52]
Hi.
I'm writing sbt plugin and I want to send reports on Slack. Sbt plugins in version 0.13 are using Scala 2.10. 
Can you publish version Scala 2.10?

**Comment by gilbertw1** [comment]
Sure! I'll verify there are no issues cross compiling, and barring any issues will push 2.10 support in the next few days.

**Comment by gilbertw1** [comment]
Hi, sorry I'm just getting back to you on this issue. Unfortunately `akka-http` isn't available for Scala 2.10 and we use it for all the Rest calls and the websocket connection.

It might be possible to compile an older version of `slack-scala-client` for 2.10, back when it relied on `dispatch` for REST and `spray-websocket` for the websocket support.
