### ISSUE TITLE
Can't work behind proxy.

### ISSUE THREAD

**Issue by Hungsiro506** [gilbertw1/slack-scala-client#56]
I can not create any client (blocking client, async client or  rtm) behind proxy. How could i solver it .

**Comment by gilbertw1** [comment]
Unfortunately it looks like `akka-http`, which we're using for all of our http calls and websocket support, does not currently support proxies. Once support is added, it looks like you could simply add configuration in an `application.conf` file to use a proxy. 

You can find the relevent `akka-http` issue here: https://github.com/akka/akka-http/issues/115
