### ISSUE TITLE
getUserInfo implements wrong endpoint

### ISSUE THREAD

**Issue by man1** [gilbertw1/slack-scala-client#6]
I get a `slack.api.ApiError: unknown_method` exception from SlackApiClient's getUserInfo(). I think the right endpoint is "users.info", not "users.getInfo".

This project is awesome, thanks!

**Comment by gilbertw1** [comment]
Thanks for reporting this issue, and I'm glad you like the project! Just fixed this in master, I'll be publishing a new version to maven central before long.
