### ISSUE TITLE
Question marks

### ISSUE THREAD

**Issue by Tenchi2xh** [gilbertw1/slack-scala-client#60]
Posting a message containing a question mark breaks the query URL:

```scala
client.postChatMessage(channelId, "?")
slack.api.InvalidResponseError: Bad status code from Slack: 404
```

URL-encoding or HTML-escaping it doesn't help either as Slack doesn't decode it on the other side

**Comment by gilbertw1** [comment]
Interesting, I think this may be a bug on Slack's end. After the first '?', subsequent question marks are treated as literal characters and should not have any significance. It's possible that there is a bug in Slack's http parsing logic. 

Either way, I'll look into it. Thanks for reporting!

For reference: https://tools.ietf.org/html/rfc3986#section-3.4

**Comment by gilbertw1** [comment]
After some research into the subject, I was able to create a temporary (read: hacky) workaround to url encode question marks in `akka-http`. This will solve the immediate problem, while I look into a longer term more robust solution.
