### ISSUE TITLE
Cannot specify username in posting message

### ISSUE THREAD

**Issue by bigwheel** [gilbertw1/slack-scala-client#8]
https://github.com/gilbertw1/slack-scala-client/blob/816a0819eff01c45adce73e9151b3e999611b3ce/src/main/scala/slack/api/SlackApiClient.scala#L191-L208

method 'postChatMessage' accepts username argument, but doesnt use it.

**Comment by gilbertw1** [comment]
Thanks for reporting this! I've fixed it in master and I'll release a new version later today.

**Comment by bigwheel** [comment]
ty for early response.
